"""Add weight_logs table

Revision ID: 52adc25a1c76
Revises: 1dfa0f840923
Create Date: 2025-12-25 23:14:56.420779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52adc25a1c76'
down_revision: Union[str, None] = '1dfa0f840923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
