"""add_water_tracking

Revision ID: 938abe9e0d6d
Revises: 52adc25a1c76
Create Date: 2025-12-26 13:17:17.452320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938abe9e0d6d'
down_revision: Union[str, None] = '52adc25a1c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('daily_water_goal_ml', sa.Integer(), nullable=True))

    # Create water_logs table if it doesn't exist
    # Note: Table may already exist from a previous migration or manual creation
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'water_logs' not in inspector.get_table_names():
        op.create_table(
            'water_logs',
            sa.Column('id', sa.UUID(as_uuid=False), primary_key=True),
            sa.Column('user_id', sa.UUID(as_uuid=False), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
            sa.Column('amount_ml', sa.Integer(), nullable=False),
            sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column('source', sa.String(50), nullable=True),
        )
        op.create_index('ix_water_logs_user_id', 'water_logs', ['user_id'])
        op.create_index('ix_water_logs_logged_at', 'water_logs', ['logged_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_water_logs_logged_at', 'water_logs')
    op.drop_index('ix_water_logs_user_id', 'water_logs')
    op.drop_table('water_logs')
    op.drop_column('user_profiles', 'daily_water_goal_ml')
    # ### end Alembic commands ###
