"""add_streak_fields_to_user_profile

Revision ID: a19fda09d433
Revises: ccf87764aa69
Create Date: 2025-12-26 14:33:01.696941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19fda09d433'
down_revision: Union[str, None] = 'ccf87764aa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first with server defaults
    op.add_column('user_profiles', sa.Column('current_streak', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user_profiles', sa.Column('longest_streak', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('user_profiles', sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profiles', sa.Column('streak_grace_hours', sa.Integer(), nullable=True, server_default='36'))

    # Update any existing NULL values to defaults
    op.execute("UPDATE user_profiles SET current_streak = 0 WHERE current_streak IS NULL")
    op.execute("UPDATE user_profiles SET longest_streak = 0 WHERE longest_streak IS NULL")
    op.execute("UPDATE user_profiles SET streak_grace_hours = 36 WHERE streak_grace_hours IS NULL")

    # Now make columns NOT NULL and remove server defaults
    op.alter_column('user_profiles', 'current_streak', nullable=False)
    op.alter_column('user_profiles', 'longest_streak', nullable=False)
    op.alter_column('user_profiles', 'streak_grace_hours', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'streak_grace_hours')
    op.drop_column('user_profiles', 'last_activity_date')
    op.drop_column('user_profiles', 'longest_streak')
    op.drop_column('user_profiles', 'current_streak')
    # ### end Alembic commands ###
