"""add_vitamin_mineral_fields_to_meal_logs

Revision ID: c3f0981e0d77
Revises: b4744e66b920
Create Date: 2025-12-29 16:15:43.116673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f0981e0d77'
down_revision: Union[str, None] = 'b4744e66b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_logs', sa.Column('vitamin_a_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_c_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_d_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_e_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_k_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b1_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b2_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b3_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b6_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b9_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('vitamin_b12_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('calcium_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('iron_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('magnesium_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('phosphorus_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('potassium_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('zinc_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('selenium_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('copper_mcg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('manganese_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('health_score', sa.Integer(), nullable=True))
    op.add_column('meal_logs', sa.Column('health_score_breakdown', sa.JSON(), nullable=True))
    op.add_column('meal_logs', sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meal_logs', sa.Column('synergy_insights', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('weight_goal_kg', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_rate_kg_per_week', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('goal_target_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'goal_target_date')
    op.drop_column('user_profiles', 'target_rate_kg_per_week')
    op.drop_column('user_profiles', 'weight_goal_kg')
    op.drop_column('meal_logs', 'synergy_insights')
    op.drop_column('meal_logs', 'ai_analyzed_at')
    op.drop_column('meal_logs', 'health_score_breakdown')
    op.drop_column('meal_logs', 'health_score')
    op.drop_column('meal_logs', 'manganese_mg_est')
    op.drop_column('meal_logs', 'copper_mcg_est')
    op.drop_column('meal_logs', 'selenium_mcg_est')
    op.drop_column('meal_logs', 'zinc_mg_est')
    op.drop_column('meal_logs', 'potassium_mg_est')
    op.drop_column('meal_logs', 'phosphorus_mg_est')
    op.drop_column('meal_logs', 'magnesium_mg_est')
    op.drop_column('meal_logs', 'iron_mg_est')
    op.drop_column('meal_logs', 'calcium_mg_est')
    op.drop_column('meal_logs', 'vitamin_b12_mcg_est')
    op.drop_column('meal_logs', 'vitamin_b9_mcg_est')
    op.drop_column('meal_logs', 'vitamin_b6_mg_est')
    op.drop_column('meal_logs', 'vitamin_b3_mg_est')
    op.drop_column('meal_logs', 'vitamin_b2_mg_est')
    op.drop_column('meal_logs', 'vitamin_b1_mg_est')
    op.drop_column('meal_logs', 'vitamin_k_mcg_est')
    op.drop_column('meal_logs', 'vitamin_e_mg_est')
    op.drop_column('meal_logs', 'vitamin_d_mcg_est')
    op.drop_column('meal_logs', 'vitamin_c_mg_est')
    op.drop_column('meal_logs', 'vitamin_a_mcg_est')
    # ### end Alembic commands ###
