"""add_micronutrients_to_meal_logs

Revision ID: ccf87764aa69
Revises: 938abe9e0d6d
Create Date: 2025-12-26 14:24:15.406954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf87764aa69'
down_revision: Union[str, None] = '938abe9e0d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_logs', sa.Column('sodium_mg_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('saturated_fat_g_est', sa.Float(), nullable=True))
    op.add_column('meal_logs', sa.Column('cholesterol_mg_est', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_logs', 'cholesterol_mg_est')
    op.drop_column('meal_logs', 'saturated_fat_g_est')
    op.drop_column('meal_logs', 'sodium_mg_est')
    # ### end Alembic commands ###
