"""add_injuries_medical_conditions_preferred_ingredients_to_profile

Revision ID: fb7763c82162
Revises: b9b1db28217d
Create Date: 2025-12-29 19:41:18.172515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7763c82162'
down_revision: Union[str, None] = 'b9b1db28217d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('injuries', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('medical_conditions', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_ingredients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_ingredients')
    op.drop_column('user_profiles', 'medical_conditions')
    op.drop_column('user_profiles', 'injuries')
    # ### end Alembic commands ###
